
services:
  discovery-service:
    container_name: discovery-service
    build: ./discovery-service
    ports:
      - "8761:8761"
    networks:
      - microservice-net

  config-service:
    container_name: config-service
    build: ./config-service
    ports:
      - "8888:8888"
    healthcheck:
      test: ["CMD","curl","-f","http://localhost:8888/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - microservice-net

  gateway-service:
    container_name: gateway-service
    build: ./gateway-service
    ports:
      - "8080:8080"
    depends_on:
      config-service:
        condition: service_healthy
    networks:
      - microservice-net

  user-service:
    container_name: user-service
    build: ./user-service
    ports:
      - "8081:8081"
    depends_on:
      config-service:
        condition: service_healthy
    networks:
      - microservice-net

  user-service-db:
    container_name: user-service-db
    image: postgres
    ports:
      - "5433:5432"

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=user
      - POSTGRES_PASSWORD=root

    volumes:
      - pg_data_user:/var/lib/postgresql

    networks:
      - microservice-net

  event-service-db:
    container_name: event-service-db
    image: postgres
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=event
      - POSTGRES_PASSWORD=root
    volumes:
      - pg_data_event:/var/lib/postgresql
    networks:
      - microservice-net


  auth-service-db:
    container_name: auth-service-db
    image: redis
    ports:
      - "6379:6379"
    networks:
      - microservice-net

  auth-service:
    build: ./auth-service
    depends_on:
      config-service:
        condition: service_healthy
    container_name: auth-service
    ports:
      - "8082:8082"
    networks:
      - microservice-net

  event-service:
    build: ./event-service
    depends_on:
      config-service:
        condition: service_healthy
      event-service-db:
        condition: service_started
      rabbitmq:
        condition: service_started
    container_name: event-service
    ports:
      - "8083:8083"
    networks:
      - microservice-net

  ticket-service:
    build: ./ticket-service
    depends_on:
      config-service:
        condition: service_healthy
      ticket-service-db:
        condition: service_started
      rabbitmq:
        condition: service_started
    container_name: ticket-service
    ports:
      - "8084:8084"
    networks:
      - microservice-net

  ticket-service-db:
    container_name: ticket-service-db
    image: postgres
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=ticket
      - POSTGRES_PASSWORD=root
    volumes:
      - pg_data_ticket:/var/lib/postgresql
    networks:
      - microservice-net

  rabbitmq:
    container_name: rabbitmq
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - microservice-net

networks:
  microservice-net:

volumes:
  pg_data_user:
  pg_data_ticket:
  pg_data_event: